# Generated by Django 5.2.9 on 2025-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmtask",
            name="description",
        ),
        migrations.AddField(
            model_name="farmtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("planting", "Planting"),
                    ("watering", "Watering"),
                    ("fertilizing", "Fertilizing"),
                    ("harvesting", "Harvesting"),
                ],
                default="planting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="farmtask",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
