# Generated by Django 5.2.9 on 2025-12-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symptoms", models.TextField()),
                ("treatment", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="pests/")),
                (
                    "plants",
                    models.ManyToManyField(related_name="pests", to="pests.plant"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cause", models.TextField()),
                ("symptoms", models.TextField()),
                ("treatment", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="diseases/"),
                ),
                (
                    "plants",
                    models.ManyToManyField(related_name="diseases", to="pests.plant"),
                ),
            ],
        ),
    ]
