# Generated by Django 5.2.9 on 2025-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plants/"),
        ),
    ]
